name: Paardenarts Joost Hezemans
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7733
title: Paardenarts Joost Hezemans
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76215825-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#8a9ebf'
    - '#ced9eb'
    - '#889b1d'
    - '#8d4214'
  brandStrength: 0.6722575144376606
  lightness: 0.8314457356464118
  saturation: 0.9788610520772636
  rhythmicContrast: 0.75
purpose: []
