name: Paardenarts Joost Hezemans
favicon: null
layout_spectrum: 0.7843139364849776
typography_spectrum: 0.17191907693631947
title: Paardenarts Joost Hezemans
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6722575144376606
  lightness: 0.8314457356464118
  saturation: 0.9788610520772636
  rhythmicContrast: 0.9180024648085237
purpose: []
