name: Paardenarts Joost Hezemans
favicon: null
layout_spectrum: 0.64395
typography_spectrum: 0.22532
title: Paardenarts Joost Hezemans
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76215825-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#181818'
    - '#656565'
    - '#919191'
    - '#c9c9c9'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.9788610520772636
  rhythmicContrast: 0.5
purpose: []
